### ISSUE TITLE
Building on debian buster fails

### ISSUE THREAD

**Issue by cs35-owncloud** [barnumbirr/scaphandre-debian#1]
Hi,

first thanks for your work ! I tried it on Debian Bullseye and it's working well.

I tried to compile scaphandre for Debian Buster but it's failing:

```
$ ./build.sh -i debian:buster-slim
...
   Compiling curl-sys v0.4.47+curl-7.79.0
   Compiling ring v0.16.20
   Compiling quote v1.0.9
   Compiling socket2 v0.4.2
   Compiling getrandom v0.2.3
error: attributes are not yet allowed on `if` expressions
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.2/src/sys/unix.rs:879:5
    |
879 |     #[cfg(not(any(target_os = "haiku", target_os = "openbsd")))]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `socket2`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make[1]: *** [debian/rules:10: override_dh_auto_build] Error 101
make[1]: Leaving directory '/tmp/tmp.94KqjbUYow/scaphandre'
make: *** [debian/rules:4: build] Error 2
```

Do you have any idea on how to compile scaphandre for Debian Buster ?
Thanks.

**Comment by barnumbirr** [comment]
Hi,

this isn't really a `scaphandre-debian` issue but here you go:
Buster ships with `rustc 1.41.1` however socket2 requires at least `rustc 1.46`.
Update `rustc` and you should be good to go.

Cheers.

**Comment by cs35-owncloud** [comment]
Hello,

thanks for your answer and your hint, sadly I couldn't succeed to build scaphandre with your script on several Debian oses, I still had some errors that I couldn't manage to fix.
So in the end I tried in a different way:

```
#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >/tmp/rustup.sh
bash /tmp/rustup.sh -y
export PATH="$HOME/.cargo/bin:$PATH"
rustup install 1.48
rustup default 1.48
cd /usr/src
git clone https://github.com/hubblo-org/scaphandre.git
cd scaphandre
cargo build --release
target/release/scaphandre --version
```

I could manage to use it on gitlab to build every Debian version I needed. I will pack it with [fpm](https://fpm.readthedocs.io/en/v1.13.1/) to have my debs.

Thanks a lot for your help !

**Comment by barnumbirr** [comment]
Glad you figured it out. You could also [have tweaked `entrypoint.sh` to make it work.](https://github.com/barnumbirr/scaphandre-debian/blob/b30f5be1cdabd69bc76177a21a47b4fa0f660497/entrypoint.sh)

**Comment by cs35-owncloud** [comment]
I tried and did, but well, errors were still popping that I was unable to fix by myself, and I didn't want to bother you ;)
Thanks.
